server:
  port: 8080

spring:
  application:
    name: config-server
  config:
    import:
    - optional:configserver:http://localhost/8888/
  cloud:
    config:
      profile: default 

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'

greeting-service:
  greeting: "Olá"
  default-value: "Mundo"