server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:AldrinRicardo/microservices.git
          #username: username
          #password: password
          default-label: main
          search-paths:
          - 'greeting-service*'